security:
    # 1. Gestion du hachage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # 2. Définition du User Provider (C'est ce qui manque chez toi !)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            
            # Configuration de ton Authenticator personnalisé
            custom_authenticator: App\Security\UserAuthAuthenticator
            
            logout:
                path: app_logout
                # redirect to: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # Contrôle d'accès simple
    access_control:
        - { path: ^/checkout, roles: ROLE_USER }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }